[tool.poetry]
name = "protools"
version = "0.1.0"
description = "Convenience tools to manage projects with Python."
authors = ["Jesse P. Johnson <jpj6652@gmail.com>"]
readme = "README.md"
classifiers = ["License :: OSI Approved :: Apache Software License"]
include = ["protools/_vendor/gitignore", "protools/templates"]

[tool.poetry.dependencies]
python = "^3.6.2"
jinja2 = "^2.11.2"
invoke = "^1.5.0"
compendium = "^0.1.1-alpha.0"
python-gnupg = "^0.4.7"
proman-common = "^0.1.1-alpha.1"
editables = "^0.2"
stevedore = "^3.4.0"
briefcase = "^0.3.5"
pygit2 = "^1.6.1"
PyInputPlus = "^0.2.12"
keyring = "^23.2.1"
SecretStorage = {version = "^3.3.1", platform = "linux"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
pydocstyle = "^5.0.2"
docstr-coverage = "^1.2.0"
pytest-cov = "^2.10.0"
isort = "^5.9.2"
bandit = "^1.6.2"
safety = "^1.9.0"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.0"
mkdocstrings = "^0.15.2"
mypy = "^0.910"
pyfakefs = "^4.5.0"
types-Jinja2 = "^2.11.2"
tox = "^3.24.0"
black = "^21.7b0"
python-gilt = "^1.2.3"

# [tool.poetry.extras]
# gnome = ["secretstorage"]
twine = "^3.5.0"
# kde = ["dbus-python"]

[tool.poetry.plugins."proman.precommit.validate"]
conventional_commits = "protools:precommit"

[tool.poetry.plugins."proman.workflow.pki"]
gpg = "protools.pki.gpg:namespace"
tls = "protools.pki.tls:namespace"

[tool.poetry.plugins."proman.workflow.vcs"]
git = "protools.git:namespace"

[tool.poetry.plugins."proman.workflow.package"]
flit = "protools.package.flit:namespace"
poetry = "protools.package.poetry:namespace"
setuptools = "protools.package.setuptools:namespace"
twine = "protools.package.twine:namespace"

[tool.poetry.plugins."proman.workflow.executable"]
briefcase = "protools.executable.briefcase:namespace"
# pyinstaller = "protools.executable.pyinstaller:namespace"

[tool.poetry.plugins."proman.workflow.lint"]
flake8 = "protools.qa.flake8:namespace"

[tool.poetry.plugins."proman.workflow.formatter"]
autopep8 = "protools.qa.autopep8:namespace"
black = "protools.qa.black:namespace"
isort = "protools.qa.isort:namespace"

[tool.poetry.plugins."proman.workflow.unit_tests"]
pytest = "protools.qa.pytest:namespace"

# [tool.poetry.plugins."proman.workflow.coverage"]
# pytest = "protools.qa.pytest:namespace"

[tool.poetry.plugins."proman.workflow.typing"]
mypy = "protools.qa.mypy:namespace"

[tool.poetry.plugins."proman.workflow.sca"]
bandit = "protools.security.bandit:namespace"
safety = "protools.security.safety:namespace"

[tool.poetry.plugins."proman.workflow.container"]
docker = "protools.container.docker:namespace"
podman = "protools.container.podman:namespace"

[tool.poetry.plugins."proman.workflow.docs"]
mkdocs = "protools.docs.mkdocs:namespace"

[tool.poetry.plugins."proman.workflow.integration"]

[tool.poetry.scripts]
protools-workflow = "protools:protools.run"
protools = "protools:tools.run"

# TODO: deprecate flit
# [tool.flit.metadata]
# module = "protools"
# author = "Jesse P. Johnson"
# author-email = "jpj6652@gmail.com"
# home-page = "https://github.com/proman/proman-workflows"
# requires = ["compendium", "invoke", "keyring", "jinja2", "proman-common", "stevedore"]
# classifiers = ["License :: OSI Approved :: Apache Software License"]
#
# [tool.flit.entrypoints."proman.precommit.validate"]
# conventional_commits = "protools:precommit"
#
# [tool.flit.scripts]
# project = "protools:project.run"
# workflow = "protools:workflow.run"

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
ling-length = 79
include = '\.pyi?$'
exclude = '''

(
  /(
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vagrant
    | _build
    | dist
  )
)
'''

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::DeprecationWarning:invoke.*:",
  "ignore::DeprecationWarning:_yaml.*:",
]

[tool.mypy]
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = true
ignore_missing_imports = true

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
# requires = ["flit_core>=2,<4"]
# build-backend = "flit_core.buildapi"
# requires = ['setuptools>=40.8.0', 'wheel']
# build-backend = 'setuptools.build_meta'
