[tool.poetry]
name = "proman_workflows"
version = "0.1.0"
description = "Convential commits parser in Python."
authors = ["Jesse P. Johnson <jpj6652@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.2"
jinja2 = "^2.11.2"
lark-parser = "^0.10.0"
transitions = "^0.8.4"
GitPython = "^3.1.17"
compendium = "^0.1.1-dev.82"
packaging = "^20.9"
invoke = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
pydocstyle = "^5.0.2"
docstr-coverage = "^1.2.0"
pytest-cov = "^2.10.0"
isort = "^5.9.2"
bandit = "^1.6.2"
safety = "^1.9.0"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.0"
mkdocstrings = "^0.15.2"
flit = "^3.2.0"
mypy = "^0.910"
pyfakefs = "^4.5.0"
types-Jinja2 = "^2.11.2"
tox = "^3.24.0"
black = "^21.7b0"

[tool.flit.metadata]
module = "proman_workflows"
author = "Jesse P. Johnson"
author-email = "jpj6652@gmail.com"
home-page = "https://github.com/proman/proman-workflows"
requires = ["argufy", "jinja2", "GitPython", "lark-parser", "transitions"]
classifiers = ["License :: OSI Approved :: Apache Software License"]

[tool.flit.entrypoints."proman.precommit.validate"]
conventional_commits = "proman_workflows:precommit"

[tool.flit.scripts]
workflow = "proman_workflows:program.run"

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
ling-length = 79
include = '\.pyi?$'
exclude = '''

(
  /(
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vagrant
    | _build
    | dist
  )
)
'''

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:invoke.*:",
    "ignore::DeprecationWarning:_yaml.*:",
]

[tool.mypy]
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = true
ignore_missing_imports = true
