[tool.poetry]
name = "git_tools"
version = "0.1.0"
description = "Convential commits parser in Python."
authors = ["Jesse P. Johnson <jpj6652@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
compendium = "^0.1.1-alpha.63"
pypyr = "^4.0.0"
jinja2 = "^2.11.2"
argufy = "^0.1.1-alpha.11"
lark-parser = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
pydocstyle = "^5.0.2"
docstr-coverage = "^1.2.0"
pytest-cov = "^2.10.0"
isort = "^4.3.21"
bandit = "^1.6.2"
safety = "^1.9.0"
mkdocs = "^1.1.2"
bump2version = "^1.0.0"
invoke = "^1.4.1"
mkdocs-material = "^5.4.0"
flit = "^2.3.0"

[tool.flit.metadata]
module = "git_tools"
author = "Jesse P. Johnson"
author-email = "jpj6652@gmail.com"
home-page = "https://github.com/kuwv/python-convential-commits-parser"
requires = []

classifiers = ["License :: OSI Approved :: Apache Software License"]

[tool.flit.scripts]
git-tools = "git_tools.__main__:main"

[tool.black]
include = '\.pyi?$'
exclude = '''

(
  /(
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vagrant
    | _build
    | dist
  )
)
'''
