[bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"example/__init__.py" = [
    "__version__ = '{version}'",
]
