[tool.proman]
authors = ["Jesse P. Johnson"]
description = "A mock project for development."
name = "mock-project"
version = "2.6.5"

[tool.proman.release]
enable_devreleases = true
enable_prereleases = true
enable_postreleases = true

[[tool.proman.release.files]]
filepath = "example/__init__.py"
pattern = "__version__ = '${version}'"

[[tool.proman.release.files]]
filepath = "pyproject.toml"
pattern = "version = \"${version}\""

[tool.proman.dependencies]
idna = "3.1"

[tool.proman.dev-dependencies]
