---
name: Python package
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Lint
        run: |
          poetry run workflow-tools style.sort-headers.run --check
          poetry run workflow-tools style.format.run --check
          poetry run workflow-tools sca.lint.run
          poetry run workflow-tools sca.type-checking.run
      # - name: Perform security checks
      #   run: |
      #     poetry run workflow-tools sec.sast.run
      #     poetry run workflow-tools sec.dependency-scan.run
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Perform build
        run: poetry run workflow-tools dist.package.build
      - name: Perform publish
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi "${{ secrets.TESTPYPI_TOKEN }}"
          poetry run workflow-tools --echo dist.package.publish
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ['3.7', '3.8', '3.9', '3.10']
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: "Set up Python 3.10"
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.10
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install poetry
  #     - name: Install package fro test-pypi
  #       run: python3 -m pip install --index-url https://test.pypi.org/simple/
  #     # - name: Perform tests
  #     #   run: poetry run workflow-tools qa.unit-test.run

